# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-28 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('ipaddr', models.CharField(blank=True, max_length=200, null=True)),
                ('action', models.CharField(max_length=500)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('app', models.CharField(max_length=100)),
            ],
        ),
    ]
