# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-28 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contentUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=500)),
            ],
            options={
                'permissions': (('view_contenturl', 'View contenturl'),),
            },
        ),
        migrations.CreateModel(
            name='mainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=500)),
            ],
            options={
                'permissions': (('view_mainmenu', 'View mainmenu'),),
            },
        ),
        migrations.CreateModel(
            name='subMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=500)),
                ('parentMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.mainMenu')),
            ],
            options={
                'permissions': (('view_submenu', 'View submenu'),),
            },
        ),
        migrations.AddField(
            model_name='contenturl',
            name='parentMenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.subMenu'),
        ),
    ]
